export const GUIDE_SIGNIN_REQUEST = 'GUIDE_SIGNIN_REQUEST';
export const GUIDE_SIGNIN_SUCCESS = 'GUIDE_SIGNIN_SUCCESS';
export const GUIDE_SIGNIN_FAIL = 'GUIDE_SIGNIN_FAIL';
export const GUIDE_SIGNOUT = 'GUIDE_SIGNOUT';
