export const HOTELBOOKING_LIST_REQUEST = 'HOTELBOOKING_LIST_REQUEST';
export const HOTELBOOKING_LIST_SUCCESS = 'HOTELBOOKING_LIST_SUCCESS';
export const HOTELBOOKING_LIST_FAIL = 'HOTELBOOKING_LIST_FAIL';

export const MYHOTELBOOKING_LIST_REQUEST = 'MYHOTELBOOKING_LIST_REQUEST';
export const MYHOTELBOOKING_LIST_SUCCESS = 'MYHOTELBOOKING_LIST_SUCCESS';
export const MYHOTELBOOKING_LIST_FAIL = 'MYHOTELBOOKING_LIST_FAIL';


export const HOTELBOOKING_DETAILS_REQUEST = 'HOTELBOOKING_DETAILS_REQUEST';
export const HOTELBOOKING_DETAILS_SUCCESS = 'HOTELBOOKING_DETAILS_SUCCESS';
export const HOTELBOOKING_DETAILS_FAIL = 'HOTELBOOKING_DETAILS_FAIL';

export const HOTELBOOKING_DAYS_REQUEST = 'HOTELBOOKING_DAYS_REQUEST';
export const HOTELBOOKING_DAYS_SUCCESS = 'HOTELBOOKING_DAYS_SUCCESS';
export const HOTELBOOKING_DAYS_FAIL = 'HOTELBOOKING_DAYS_FAIL';

export const HOTELBOOKING_CREATE_REQUEST = 'HOTELBOOKING_CREATE_REQUEST';
export const HOTELBOOKING_CREATE_SUCCESS = 'HOTELBOOKING_CREATE_SUCCESS';
export const HOTELBOOKING_CREATE_FAIL = 'HOTELBOOKING_CREATE_FAIL';
export const HOTELBOOKING_CREATE_RESET = 'HOTELBOOKING_CREATE_RESET';

export const HOTELBOOKING_UPDATE_REQUEST = 'HOTELBOOKING_UPDATE_REQUEST';
export const HOTELBOOKING_UPDATE_SUCCESS = 'HOTELBOOKING_UPDATE_SUCCESS';
export const HOTELBOOKING_UPDATE_FAIL = 'HOTELBOOKING_UPDATE_FAIL';
export const HOTELBOOKING_UPDATE_RESET = 'HOTELBOOKING_UPDATE_RESET';

export const HOTELBOOKING_DELETE_REQUEST = 'HOTELBOOKING_DELETE_REQUEST';
export const HOTELBOOKING_DELETE_SUCCESS = 'HOTELBOOKING_DELETE_SUCCESS';
export const HOTELBOOKING_DELETE_FAIL = 'HOTELBOOKING_DELETE_FAIL';
export const HOTELBOOKING_DELETE_RESET = 'HOTELBOOKING_DELETE_RESET';