export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';


export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST';
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS';
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL';